development:
  adapter: postgresql
  encoding: unicode
  database: commercetest
  pool: 5
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: commercedev
  pool: 5
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: commerceprod
  pool: 5
  password: